### ISSUE TITLE
Move Link not working

### ISSUE THREAD

**Issue by craigz** [WebCrateApp/webcrate#54]
### 🏷️ WebCrate Version

v1.4.2

### ⚙️ Environment

Chrome, Safari

### 🐞 Describe the bug

In a link detail 'box', selecting `Move Link` opens the window as expected, however clicking on the dropdown menu under the "Select a crate to move the link" button performs a quick animation, then returns to the main crate page without allowing for a selection to be made. 

As far as i recall, this worked prior to the update applied today.

### 📚 To Reproduce

- click a link to expand link details
- click the disclosure icon (...) for more options
- select `Move Link`
- click the selection icon in the resulting window to pick a new destination crate.
- enjoy the animation
- view the crate contents

### 💡 Expected behavior

a list of available crates should appear, from which a selection can be made.

**Comment by BetaHuhn** [comment]
Hey, thanks for reporting this bug!

I encountered the issue as well, will fix it asap.

> As far as i recall, this worked prior to the update applied today.

This feature actually only came with that update, it didn't exist before. Previously you could only move links by dragging and dropping them to another crate :)

**Comment by craigz** [comment]
Cool. Glad it wasn't just me. I'd initially placed the blame on Safari until it was repeatable in Brave (Chromium based). 

Interesting bit of bias confirmation there! I was **sure** I'd moved via option in the past. Guess I would have just moved the card, which is what I ended up doing as a workaround anyhow.

**Comment by BetaHuhn** [comment]
> Interesting bit of bias confirmation there! I was sure I'd moved via menu option in the past. Guess I would have just moved the card, which is what I ended up doing as a workaround anyhow.

Yeah, funny how the brain works sometimes 😅 Had a similar thing happen to me a while ago with another piece of software. Swear I had used a feature in the past, but they insisted it had never existed 😂

**Comment by BetaHuhn** [comment]
This issue has been resolved in version [1.4.3](https://github.com/WebCrateApp/webcrate/releases/tag/v1.4.3) 🎉

@craigz refer to the [docs](https://webcrate.app/docs/faq#how-are-updates-handled) on how you can update to the latest version :)

**Comment by craigz** [comment]
@BetaHuhn i've just updated and can confirm it's working!

**Comment by BetaHuhn** [comment]
Great! Thanks for confirming :)

Sorry that it took so long to fix, got busy with other projects :/
