### ISSUE TITLE
Error: Cert not issued yet, please try again after a few minutes.

### ISSUE THREAD

**Issue by plsnotracking** [WebCrateApp/webcrate#63]
### 🏷️ WebCrate Version

v1.4.3

### ⚙️ Environment

Firefox

### 🐞 Describe the bug

When I click on install on the install button, it generates an error

```
Error: Cert not issued yet, please try again after a few minutes. If the error
persists, please login again and contact us.
```

Either it's the platform or there's an issue with the installation of the app on the platform, any guidance would be appreciated.

### 📚 To Reproduce

Just sign up on deta, and login.
After login, install WebCrate.

### 💡 Expected behavior

Should install.

### 📋 Additional context

<img width="894" alt="Error" src="https://user-images.githubusercontent.com/54467867/174693747-77d3a8fe-899c-4be4-844d-37f386e9f727.png">

**Comment by aavshr** [comment]
hello @plsnotracking, from Deta here. Very sorry you experienced this error.

Does the issue persist after logging out and logging in again?

**Comment by vivekpatani** [comment]
hello @aavshr it didn't immediately fix itself, but I checked the next day, and it was gone.

Tried immediately logging in and out on different browsers, didn't help. Give it some time.

**Comment by BetaHuhn** [comment]
@ed-bog are you still having this issue?
