### ISSUE TITLE
Browser extension not available in the Firefox add-on store

### ISSUE THREAD

**Issue by plsnotracking** [WebCrateApp/webcrate#64]
https://addons.mozilla.org/en-US/firefox/addon/webcrate/

Please let me know if I'm missing something, thanks!

**Comment by BetaHuhn** [comment]
Hey @plsnotracking,

how did you manage to create an issue in the https://github.com/WebCrateApp/browser-extension repo? It should have redirected you to the main https://github.com/WebCrateApp/webcrate repo where you can create a new issue/discussion: https://github.com/WebCrateApp/webcrate/issues/new/choose

Regarding the Firefox addon, it looks like Mozilla took it down again. The same happened to the Chrome extension recently as well, see https://github.com/WebCrateApp/webcrate/discussions/61.

I will resubmit the extension and I hope it gets approved soon (usually takes 2-3 weeks).

In the meantime, you can try to install the extension manually by following the instructions in the [README](https://github.com/WebCrateApp/browser-extension#-building-the-extension-manually).

Sorry for the inconvenience!

**Comment by plsnotracking** [comment]
@betahuhn tbh, I've no idea, can't seem to redo it, and it has skipped my head on how to actually do it.

**Comment by BetaHuhn** [comment]
No problem! Was just wondering 😄

**Comment by plsnotracking** [comment]
@BetaHuhn any word? Seems like the FF extension is still not available. Thanks.

**Comment by plsnotracking** [comment]
Seems like this is not going to happen any time soon, will close it out. Thanks.
