### ISSUE TITLE
Doc about accessing needs update

### ISSUE THREAD

**Issue by CofinCup** [WebCrateApp/webcrate#70]
### 🏷️ WebCrate Version

v1.5.2

### ⚙️ Environment

Chrome

### 🐞 Describe the bug

Due to the [new deta space change](https://deta.space/blog/merging-space), new webcrate app instances could not be accessed in the old way **alias.username.deta.app.**, and old apps are unable to be accessed in the same way by **February 13th**:
> Under the old system, a Space app was available under alias.username.deta.app. This means if you share a link to your Space app, it will expose your Deta username. For some users this may be ok, but we want the default on Space to be as secure and private as possible. We also had to generate one SSL certificate per user, and we’ve been having reliability issues on this front.
> 
>Going forward, to fix these issues, all Space apps have new a domain in the following format: alias-random.deta.app. Each app gets its own random suffix, which will make it much harder to guess an app’s domain. We are also moved from double subdomains to single subdomains. This makes issuing SSL certificates easier and further improves security, as all a user’s apps get their own site.

_I spent a full afternoon to find out why the website could not be accessed in the old way lol, deta docs are always splattered around_

### 📚 To Reproduce

Opening a new app, we would get a domain like this: webcrate-1-b8374455.deta.app

### 💡 Expected behavior

Docs needed to be updated (_and maybe we should find a way to work around this problem, as the new domain is toooooo hard to remember_)

**Comment by BetaHuhn** [comment]
Hey @CofinCup,

sorry for the inconvenience! As you read in the Space blog post, Space is now using a different domain structure for improved security and reliability which also effects WebCrate.

I have updated WebCrate's docs to replace any mentions of the old domains and will pin an issue to this repo informing others of the change.

The easiest way access your WebCrate instance going forward is through the new [Space Canvas](https://deta.space). You can launch the WebCrate app from there and also install and use all the other cool Space apps. I will work on fixing `open.webcrate.app` so you can have direct access to your WebCrate instance again.

There is now also a [Space Manual](https://deta.space/manual) which contains explainers and guides all around Space itself which might be helpful to you or others.

Hope this helps, let me know if you have any questions!
